#
# ==== General info ====
#
# * After editing of this file you need to check server logs to be
# sure that no errors was appeared.
#

#
# Show debug info. Possible values: true | false (default = false)
#
# This option can affect the performance.
#
debug: false

#
# Enable main features. Possible values: true | false (default = false)
#
enabled: true

#
# Show a warning when periodic updates take more time than expected.
#
# When reporting to the plugin Author with details about
# the village info, other plugins, previous log records, etc.,
# you may request an improvement of the plugin for your server.
#
# Possible values: 1 ... 3600_000.
# Default value: 50.
#
timeout-in-ms: 50