name: CustomVillage
main: com.gmail.uprial.customvillage.CustomVillage
version: 0.1.13
api-version: 1.14
commands:
  customvillage:
      description: Reload CustomVillage config
      usage: /customvillage help
      permission:
      permission-message:
permissions:
  customvillage.reload:
        description: Gives access to CustomVillage 'reload' command
        default: op
  customvillage.info:
    description: Gives access to CustomVillage 'info' command
    default: op
  customvillage.optimize:
    description: Gives access to CustomVillage 'optimize' command
    default: op